### ISSUE TITLE
Missing required uglifyjs-webpack-plugin for development mode

### ISSUE THREAD

**Issue by laughnan** [hussainweb/drupal-bootstrap-webpack#2]
After running `yarn install`:
```
yarn install v1.13.0
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
✨  Done in 32.45s.
```
Then running `yarn run dev`:
```
yarn run v1.13.0
$ NODE_ENV=dev webpack
✖ ｢config｣: An error occurred while trying to find a config file
              Did you forget to specify a --require?
/drupal/themes/custom/my_custom_theme/node_modules/@webpack-contrib/config-loader/lib/load.js:85
    throw new LoadConfigError(e, configPath);
    ^

LoadConfigError: Cannot find module 'uglifyjs-webpack-plugin'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (/drupal/themes/custom/my_custom_theme/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/drupal/themes/custom/my_custom_theme/webpack.config.js:9:24)
    at Module._compile (/drupal/themes/custom/my_custom_theme/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (/drupal/themes/custom/my_custom_theme/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at module.exports.moduleId (/drupal/themes/custom/my_custom_theme/node_modules/import-fresh/index.js:28:9)
    at loadJs (/drupal/themes/custom/my_custom_theme/node_modules/cosmiconfig/dist/loaders.js:9:18)
    at Explorer.loadFileContent (/drupal/themes/custom/my_custom_theme/node_modules/cosmiconfig/dist/createExplorer.js:226:12)
    at Explorer.createCosmiconfigResultSync (/drupal/themes/custom/my_custom_theme/node_modules/cosmiconfig/dist/createExplorer.js:259:31)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by laughnan** [comment]
Also, thank YOU for building this. I was going to create my own on top of the `bootstrap` theme and your script fit the requirements perfectly! 💯 👍

**Comment by hussainweb** [comment]
Thank you for reporting this and contributing the fix. I have merged the PR, tested it, and it works as expected.
